// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJsqSuVhAKFDEBdT_p9RPPzMPb-MKLPJY',
    appId: '1:552166061659:web:2be23adda1a1373dec317e',
    messagingSenderId: '552166061659',
    projectId: 'kushi-phy-3fa43',
    authDomain: 'kushi-phy-3fa43.firebaseapp.com',
    storageBucket: 'kushi-phy-3fa43.appspot.com',
    measurementId: 'G-R8XK5QSFJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPqXbYpVfOS6n3w-QR0s62GK13c3w4j5U',
    appId: '1:552166061659:android:edd9980d52713b84ec317e',
    messagingSenderId: '552166061659',
    projectId: 'kushi-phy-3fa43',
    storageBucket: 'kushi-phy-3fa43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz7TxIeOSTcfd-n2OcJEE9cm201HapU3A',
    appId: '1:552166061659:ios:e99178ecb3a8d5efec317e',
    messagingSenderId: '552166061659',
    projectId: 'kushi-phy-3fa43',
    storageBucket: 'kushi-phy-3fa43.appspot.com',
    androidClientId: '552166061659-7hpdnonvaum41hvevkr3gmp7g7q3kpe7.apps.googleusercontent.com',
    iosBundleId: 'com.example.work',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz7TxIeOSTcfd-n2OcJEE9cm201HapU3A',
    appId: '1:552166061659:ios:e99178ecb3a8d5efec317e',
    messagingSenderId: '552166061659',
    projectId: 'kushi-phy-3fa43',
    storageBucket: 'kushi-phy-3fa43.appspot.com',
    androidClientId: '552166061659-7hpdnonvaum41hvevkr3gmp7g7q3kpe7.apps.googleusercontent.com',
    iosBundleId: 'com.example.work',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJsqSuVhAKFDEBdT_p9RPPzMPb-MKLPJY',
    appId: '1:552166061659:web:2be23adda1a1373dec317e',
    messagingSenderId: '552166061659',
    projectId: 'kushi-phy-3fa43',
    authDomain: 'kushi-phy-3fa43.firebaseapp.com',
    storageBucket: 'kushi-phy-3fa43.appspot.com',
    measurementId: 'G-R8XK5QSFJE',
  );

}